CREATE OR REPLACE PROCEDURE control.p_source_table_column_update("TABLE_NAME" VARCHAR, "SOURCE_COLUMN_NAME" VARCHAR, "NEW_SOURCE_COLUMN" VARCHAR, "TARGET_COLUMN_NAME" VARCHAR, "NEW_TARGET_COLUMN_NAME" VARCHAR, "DATA_TYPE" VARCHAR, "DATA_SIZE" NUMBER, "PRECISION" NUMBER, "DEFAULT_VALUE" VARCHAR, "NOT_NULL" BOOLEAN, "SOURCE_ORIDINAL_POSITION" NUMBER, "TARGET_ORIDINAL_POSITION" NUMBER, "IS_ACTIVE" BOOLEAN, "COMMENT" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    table_id NUMBER;
    source_table_column_id NUMBER;
    invalid_table EXCEPTION (-20001, 'Invalid Table Name, Table Not Found.');
    invalid_column EXCEPTION (-20002, 'Invalid Column Name, Column Not found.');
BEGIN
    SELECT table_id INTO :table_id FROM elt_engine.control.source
END;
$$;